apiVersion: v1
kind: Service
metadata:
  name: app1-harbor-loadbalancer-service
  labels:
    app: app1-harbor
spec:
  type: LoadBalancer
  selector:
    app: app1-harbor
  ports:
    - port: 80
      targetPort: 80