apiVersion: v1
kind: Service
metadata:
  name: webapp-harbor-loadbalancer-service
  labels:
    app: webapp
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 80
