apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-harbor  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-harbor
  template:
    metadata:
      labels:
        app: aks-harbor
    spec:
      containers:
      - name: aks-harbor
        image: demaksac.azurecr.io/mounilebharbor:73
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: aks-harbor  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-harbor